import * as React from "react";
import { DocumentationHeading } from "../../../../../components/Documentation/DocumentationHeading/DocumentationHeading";
import { DocumentationTable } from "../../../../../components/Documentation/DocumentationTable/DocumentationTable";
import { DocumentationCode as Code } from "../../../../../components/Documentation/DocumentationCode/DocumentationCode";
import { DocumentationLayout } from "../../../../../components/Documentation/DocumentationLayout/DocumentationLayout";
import { DocumentationNote } from "../../../../../components/Documentation/DocumentationNote/DocumentationNote";

export default function Page() {
	return (
		<DocumentationLayout>
			<DocumentationHeading level={1}>Y Axis</DocumentationHeading>
			<Code>{'import { YAxis } from "nanoplot/YAxis"'}</Code>
			<p className={"my-2"}>
				The YAxis component can render on the left/right side and with custom dataset support (multiple YAxis).
			</p>
			<ul className={"list-disc list-inside"}>
				<li>linear [default]</li>
				<li>categorical - Will be spaced evenly on the YAxis, When 'y' in dataset is a string.</li>
				<li>temporal - When 'y' in dataset is a javascript date object.</li>
				<li>logarithmic [Coming Soon]</li>
			</ul>
			<DocumentationHeading>Props</DocumentationHeading>
			<DocumentationTable
				columns={["Name", "Description", "Type", "Required", "Default"]}
				data={[
					{
						Name: { value: "ticks", tag: "code" },
						Description: "Control for the ticks that run along the YAxis",
						Type: `export type FromToJumps = {
	from?: From;
	to?: To;
	jumps?: Jumps;
};
export type MinMax = "min" | "max";
export type ISODuration = \`P\${string}\`;
export type Expression =
	| "auto"
	| "min"
	| "max"
	| \`\${MinMax} - \${number}\`
	| \`\${MinMax} - \${number}%\`
	| \`\${MinMax} - \${ISODuration}\`
	| \`\${MinMax} + \${number}%\`
	| \`\${MinMax} + \${number}\`
	| \`\${MinMax} + \${ISODuration}\`
	| number;
type From = "auto" | Expression | number;
type To = "auto" | Expression | number;
type Jumps = "auto" | ISODuration | number;`,
						Required: "No",
						Default: "{from: 'auto', to: 'auto', jumps: 'auto'}",
					},
					{
						Name: { value: "title", tag: "code" },
						Description: "Sets the title of the YAxis",
						Type: "string",
						Required: "No",
						Default: "-",
					},
					{
						Name: { value: "display", tag: "code" },
						Description: "Custom display function for the YAxis ticks",
						Type: "(tick) => ReactNode",
						Required: "No",
						Default: "-",
					},
					{
						Name: { value: "description", tag: "code" },
						Description: "Sets the description of the YAxis",
						Type: "string",
						Required: "No",
						Default: "-",
					},
					{
						Name: { value: "position", tag: "code" },
						Description: "Sets the position of the YAxis. Can be 'top', 'bottom', 'left', or 'right'. Default is 'left'.",
						Type: "'left' | 'right'",
						Required: "No",
						Default: "'left'",
					},
					{
						Name: { value: "dataset", tag: "code" },
						Description: "Changes the dataset used to render the YAxis",
						Type: "string",
						Required: "No",
						Default: "-",
					},
				]}
				renderers={{
					Name: (val) => {
						return val.tag === "code" ? <Code>{val.value}</Code> : val.value;
					},
					Type: (val) => <Code>{val}</Code>,
					Default: (val) => <Code>{val}</Code>,
				}}
			/>
			<DocumentationHeading level={2}>Temporal Examples</DocumentationHeading>
			<DocumentationNote>
				When using temporal ticks, these definitions are relevant.
				<br /> auto = The minimum or maximum date as defined by the dataset.
				<br /> min = the minimum date as defined by jumps and your min value.
				<br /> max = the maximum date as defined by jumps and your max value.
				<br /> ISODuration ={" "}
				<a href={"https://en.wikipedia.org/wiki/ISO_8601#Durations"} target={"_blank"} className={"text-blue-300"}>
					Wikipedia Link
				</a>
			</DocumentationNote>
			<DocumentationTable
				columns={["Snippet", "Result"]}
				data={[
					{
						Snippet: "ticks={{ from: 'auto - P1M', to: 'auto', jumps: 'P1M' }}",
						Result: `First date in dataset minus 1 month to last date defined by jumps that is above max. Jumping every 1 month.`,
					},
					{
						Snippet: "ticks={{ from: 'min - P1M', to: 'max + P1M', jumps: 'P1M' }}",
						Result: `Take min date generated by jumps, take away 1 month. Same for max. Jump every 1 months`,
					},
					{
						Snippet: "ticks={{ from: 'min - P1M15D', to: 'max + P1M15D', jumps: 'P1Y' }}",
						Result: `Take min date generated by jumps and take away 1 month 5 days. Same for max. Jump every 1 year`,
					},
					{
						Snippet: "ticks={{ from: -25, to: 100, jumps: 5 }}",
						Result: `From -25 to 100, in 5 jumps. (-25, 0, 25, 50, 75, 100)`,
					},
					{
						Snippet: "ticks={{ from: -25, to: 'auto', jumps: 'auto' }}",
						Result: `From -25 but the library will pick the most appropriate max value and number of jumps based on the dataset`,
					},
				]}
				renderers={{
					Snippet: (val) => <Code className={"whitespace-nowrap"}>{val}</Code>,
				}}
			/>
			<DocumentationHeading level={2}>Linear Examples</DocumentationHeading>
			<DocumentationTable
				columns={["Snippet", "Result"]}
				data={[
					{
						Snippet: "ticks={{ from: -25, to: 100, jumps: 5 }}",
						Result: `From -25 to 100, in 5 jumps. (-25, 0, 25, 50, 75, 100)`,
					},
					{
						Snippet: "ticks={{ from: -25 }}",
						Result: `From -25 but the library will pick the most appropriate max value and number of jumps based on the dataset`,
					},
					{
						Snippet: "ticks={{ to: 100 }}",
						Result: `The library will pick the most appropriate min value based on the dataset and the most aesthetic number of jumps to reach 100`,
					},
					{
						Snippet: "ticks={{ jumps: 5 }}",
						Result: `Library will pick min and max values based on dataset. But will get from the min to max in 5 jumps.`,
					},
					{
						Snippet: "ticks={{ from: 'auto', to: 'auto', jumps: 'auto' }}",
						Result: `The default, library picks min, max and jumps based on dataset`,
					},
					{
						Snippet: "ticks={{ from: 'min - 10', to: 'max + 50' }}",
						Result: `From the minimum value in the dataset minus 10, to the maximum value in the dataset plus 50. The library will pick the most aesthetic number of jumps.`,
					},
					{
						Snippet: "ticks={{ from: 'min - 10%', to: 'max + 50%' }}",
						Result: `From the minimum value in the dataset minus 10% of the minimum value, to the maximum value in the dataset plus 50% of the maximum value. The library will pick the most aesthetic number of jumps.`,
					},
				]}
				renderers={{
					Snippet: (val) => <Code className={"whitespace-nowrap"}>{val}</Code>,
				}}
			/>
		</DocumentationLayout>
	);
}
